# The title of the page.
title: arXiv Benchmark

# The email.
email: korzen@cs.uni-freiburg.de

# The website description. Will appear in head meta (for Google search results)
# and in the feed.xml site description 
description: >
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# The subpath of the site, e.g. /blog
baseurl: "/arxiv-benchmark"

# The base hostname & protocol for the site, e.g. http://example.com
url: "localhost:4000" 

# Social media.
# twitter_username: jekyllrb
github_username: ckorzen

# Includes.
include: ["_pages"]

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
